enum ResponseErrors {
  ICON_REQUIRED = 'ICON_REQUIRED',
  NAME_REQUIRED = 'NAME_REQUIRED',
  PRODUCT_IMAGE_REQUIRED = 'PRODUCT_IMAGE_REQUIRED',
  INVALID_ORDER_STATUS = 'INVALID_ORDER_STATUS',
}

export default ResponseErrors;
